name: 'Create Bintray Package'
author: https://github.com/benjefferies
description: 'A tool for creating bintray packages'
branding:
  color: blue
  icon: unlock
inputs:
  bintray-user:
    description: 'Bintray user used for authentication'
    required: true
  bintray-token:
    description: 'Bintray access token used for authentication'
    required: true
  owner:
    description: 'The bintray owner or organisation to create the package under'
    required: true
  repo:
    description: 'The bintray repo to create the package will live under'
    required: true
  package-name:
    description: 'The name of the package to create'
    required: true
  package-description:
    description: 'The description of the package to create'
    required: true
  package-url:
    description: 'The url of the source code'
    required: true
  package-license:
    description: 'The license of the package to create'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BINTRAY_USER: ${{ inputs.bintray-user }}
    BINTRAY_TOKEN: ${{ inputs.bintray-token }}
    BINTRAY_ORGANISATION: ${{ inputs.owner }}
    BINTRAY_REPO: ${{ inputs.repo }}
    PACKAGE_NAME: ${{ inputs.package-name }}
    PACKAGE_DESCRIPTION: ${{ inputs.package-description }}
    PACKAGE_URL: ${{ inputs.package-url }}
    PACKAGE_LICENSE: ${{ inputs.package-license }}
